### ISSUE TITLE
Blast psionico

### ISSUE THREAD

**Issue by FoxeonNebbie** [NebbieArcane/Scripts#1]
File skills.c
Function void do_blast( struct char_data *ch, char *argument, int cmd)
Righe 5708 - 5711
 if( ( potency < 14 ) && ( number( 1, 50) < GetMaxLevel( victim ) ) )
      potency-- ;
    if( ( potency < 15 ) && ( number( 1, 52) < GetMaxLevel( victim ) ) )
      potency -= 2 ;

Il check della potenza 15 (potenza che sembra non essere raggiungibile per i mortali) finisce per applicarsi sempre oltre quello della 14.
Il risultato e che ai livelli bassi se va di sfiga toglie tre livelli di potenza al blast (check 14 -1 potenza e check 15 -2 potenza) .

Forse il check era voluto per principi o altro ma non c'è il limite con la potenza > 14?

Grazie per la verifica :)

**Comment by alar77** [comment]
Grazie per aver  aperto un ticlket ma perché sul progetto scripts che col codice di nebbie non c'entra nulla :) ?
Lo riapro nel posto giusto

**Comment by FoxeonNebbie** [comment]
Perché l ho fatto al volo mentre davo assistenza al telefono al gruppo che
cambiava i sistemi di contabilizzazione magazzini su Sap in azienda.
Sono una belina. Grazie ;)

Il 10 Feb 2018 22:27, "Giovanni G" <notifications@github.com> ha scritto:
